<?php
if (!defined('ABSPATH')) exit;
$post_id=get_queried_object_id(); $project=UWSB_Renderer::project_for_post($post_id); $data=UWSB_Renderer::data_for_post($post_id); if(!$project){status_header(404);exit;}
$profile=UWSB_Profiles::get($project['profile']); $type=get_post_meta($post_id,'_uwsb_page_type',true); $plan=$data['plan']??[]; $cards=UWSB_Renderer::cards((int)$project['id']); $nav=UWSB_Renderer::nav((int)$project['id']);
?><!doctype html><html <?php language_attributes(); ?>><head><meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width,initial-scale=1"><?php wp_head(); ?></head><body class="uwsb-site <?php echo esc_attr($profile['class'].' type-'.$type); ?>">
<header class="uwsb-header"><a class="uwsb-brand" href="<?php echo esc_url(home_url('/')); ?>"><?php echo esc_html($project['name']); ?></a><nav><?php foreach($nav as $n): ?><a href="<?php echo esc_url($n['url']); ?>"><?php echo esc_html($n['label']); ?></a><?php endforeach; ?></nav></header>
<main>
<?php if($project['profile']==='bandit'): ?><div class="uwsb-strap">NO NOISE · CLEAR STRUCTURE · DIRECT ACTION</div><?php endif; ?>
<?php if($project['profile']==='master'): ?><div class="uwsb-editorial-index"><span>01</span><span><?php echo esc_html(strtoupper($type)); ?></span></div><?php endif; ?>
<section class="uwsb-hero uwsb-hero-<?php echo esc_attr($profile['hero']); ?>">
<?php if($project['profile']==='creator'): ?><div class="uwsb-hero-art"><span><?php echo UWSB_Renderer::monogram(get_the_title()); ?></span></div><?php endif; ?>
<div><span class="uwsb-kicker"><?php echo esc_html($profile['label']); ?></span><h1><?php the_title(); ?></h1><p><?php echo esc_html(get_post_meta($post_id,'_uwsb_meta_description',true)); ?></p><?php if($project['profile']==='businessman'): ?><div class="uwsb-proofbar"><span>Structured</span><span>Fact-based</span><span>Draft-first</span></div><?php endif; ?></div>
<?php if($project['profile']!=='creator'): ?><div class="uwsb-hero-art"><span><?php echo UWSB_Renderer::monogram(get_the_title()); ?></span></div><?php endif; ?>
</section>
<?php if($project['profile']==='cartel'): ?><section class="uwsb-manifesto"><span>Selected system</span><strong><?php echo esc_html($project['name']); ?></strong></section><?php endif; ?>
<?php if($type==='home'): ?><section class="uwsb-section"><h2><?php echo $project['lang']==='ru'?'Что здесь есть':'Що тут є'; ?></h2><div class="uwsb-grid"><?php foreach(array_slice($cards,0,8) as $c): ?><a class="uwsb-card" href="<?php echo esc_url($c['url']); ?>"><div class="uwsb-thumb"><?php echo UWSB_Renderer::monogram($c['name']); ?></div><h3><?php echo esc_html($c['name']); ?></h3><?php if($c['facts']): ?><p><?php echo esc_html($c['facts'][0]); ?></p><?php endif; ?><?php if($c['price']): ?><strong><?php echo esc_html($c['price']); ?></strong><?php endif; ?></a><?php endforeach; ?></div></section>
<?php elseif($type==='catalog'): ?><section class="uwsb-section"><div class="uwsb-grid"><?php foreach($cards as $c): ?><a class="uwsb-card" href="<?php echo esc_url($c['url']); ?>"><div class="uwsb-thumb"><?php echo UWSB_Renderer::monogram($c['name']); ?></div><h2><?php echo esc_html($c['name']); ?></h2><?php if($c['facts']): ?><p><?php echo esc_html($c['facts'][0]); ?></p><?php endif; ?><?php if($c['price']): ?><strong><?php echo esc_html($c['price']); ?></strong><?php endif; ?></a><?php endforeach; ?></div></section>
<?php elseif($type==='product'): $it=$plan['item']??[]; ?><section class="uwsb-section uwsb-product"><div class="uwsb-facts"><h2><?php echo $project['lang']==='ru'?'Факты':'Факти'; ?></h2><?php if(!empty($it['facts'])):?><ul><?php foreach($it['facts'] as $f):?><li><?php echo esc_html($f); ?></li><?php endforeach;?></ul><?php else:?><p><?php echo $project['lang']==='ru'?'Дополнительные характеристики не указаны.':'Додаткові характеристики не вказані.';?></p><?php endif;?></div><?php if(!empty($it['price'])):?><div class="uwsb-price"><?php echo esc_html($it['price']); ?></div><?php endif;?></section>
<?php elseif($type==='coverage'): ?><section class="uwsb-section"><h2><?php echo $project['lang']==='ru'?'Зона работы':'Зона роботи'; ?></h2><p><?php echo nl2br(esc_html($plan['geography']??'')); ?></p></section>
<?php elseif($type==='contacts'): ?><section class="uwsb-section"><h2><?php echo $project['lang']==='ru'?'Связаться':'Зв’язатися'; ?></h2><p><?php echo nl2br(esc_html($plan['contacts']??'')); ?></p></section><?php endif; ?>
<?php $links=(array)get_post_meta($post_id,'_uwsb_internal_links',true); if($links): ?><section class="uwsb-section uwsb-related"><h2><?php echo $project['lang']==='ru'?'Также смотрите':'Також дивіться'; ?></h2><div class="uwsb-links"><?php foreach($links as $lid): if(get_post_status($lid)):?><a href="<?php echo esc_url(get_permalink($lid)); ?>"><?php echo esc_html(get_the_title($lid)); ?></a><?php endif; endforeach;?></div></section><?php endif; ?>
</main><footer class="uwsb-footer"><strong><?php echo esc_html($project['name']); ?></strong><span>Site Factory · <?php echo esc_html(date('Y')); ?></span></footer><?php wp_footer(); ?></body></html>