<?php
if (!defined('ABSPATH')) { exit; }

class SFC_Admin {
    public static function init(){
        add_action('admin_menu',array(__CLASS__,'menu'));
        add_action('admin_post_sfc_generate',array(__CLASS__,'generate'));
        add_action('admin_post_sfc_retry',array(__CLASS__,'retry'));
        add_action('admin_post_sfc_seed',array(__CLASS__,'seed'));
        add_action('admin_post_sfc_create_home',array(__CLASS__,'create_home'));
        add_action('admin_post_sfc_manual',array(__CLASS__,'manual'));
        add_action('admin_enqueue_scripts',array(__CLASS__,'assets'));
    }
    public static function assets($hook){if(strpos($hook,'sfc')===false)return;wp_enqueue_style('sfc-admin',SFC_URL.'assets/css/admin.css',array(),SFC_VERSION);}
    public static function menu(){
        add_menu_page('Site Factory','Site Factory','manage_options','sfc-dashboard',array(__CLASS__,'dashboard'),'dashicons-layout',26);
        add_submenu_page('sfc-dashboard','Матрица','Матрица','manage_options','sfc-matrix',array(__CLASS__,'matrix'));
        add_submenu_page('sfc-dashboard','Очередь и логи','Очередь и логи','manage_options','sfc-queue',array(__CLASS__,'queue'));
        add_submenu_page('sfc-dashboard','Дизайн и настройки','Дизайн и настройки','manage_options','sfc-settings',array(__CLASS__,'settings'));
    }
    private static function guard(){if(!current_user_can('manage_options'))wp_die('Недостаточно прав.');check_admin_referer('sfc_action');}
    public static function dashboard(){
        if(!current_user_can('manage_options'))return; $stats=SFC_DB::get_stats();$products=wp_count_posts('sf_product');$regions=wp_count_posts('sf_region');$cities=wp_count_posts('sf_city');$pages=get_posts(array('post_type'=>'page','post_status'=>'publish','posts_per_page'=>-1,'fields'=>'ids','meta_query'=>array(array('key'=>'_sfc_managed','value'=>'1'))));
        echo '<div class="wrap sfc-admin"><h1>Site Factory</h1><div class="sfc-grid">';
        foreach(array('Товары'=>($products->publish+$products->draft),'Регионы'=>($regions->publish+$regions->draft),'Города'=>($cities->publish+$cities->draft),'Сгенерировано'=>count($pages),'В очереди'=>$stats['queued'],'Ошибки'=>$stats['failed']) as $k=>$v)echo '<div class="sfc-stat"><span>'.esc_html($k).'</span><strong>'.esc_html($v).'</strong></div>';
        echo '</div><h2>Быстрые действия</h2><p><a class="button button-primary" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=sfc_seed'),'sfc_action')).'">Загрузить базовую географию Украины</a> <a class="button" href="'.esc_url(admin_url('edit.php?post_type=sf_product')).'">Товары</a> <a class="button" href="'.esc_url(admin_url('edit.php?post_type=sf_region')).'">Регионы</a> <a class="button" href="'.esc_url(admin_url('edit.php?post_type=sf_city')).'">Города</a></p>';
        $home=(int)SFC_Settings::get('home_page_id'); echo '<div class="sfc-panel"><h2>Главная</h2>'; if($home)echo '<p>Home page: <a href="'.esc_url(get_edit_post_link($home)).'">'.esc_html(get_the_title($home)).'</a></p>'; else echo '<p>Создайте страницу-фронтенд с шорткодом <code>[sf_home]</code>.</p><p><a class="button" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=sfc_create_home'),'sfc_action')).'">Создать Home page</a></p>'; echo '</div>';
        echo '</div>';
    }
    public static function matrix(){
        if(!current_user_can('manage_options'))return;$rows=SFC_Matrix::rows();$counts=array('CREATE'=>0,'MERGE'=>0,'SKIP'=>0);foreach($rows as $r)if(isset($counts[$r['decision']]))$counts[$r['decision']]++;
        echo '<div class="wrap sfc-admin"><h1>Content Matrix</h1><p>Матрица не перебрасывает автоматически все комбинации в публикацию. Каждая строка проходит usefulness gate.</p><div class="sfc-chips">';foreach($counts as $k=>$v)echo '<span class="sfc-chip sfc-'.$k.'">'.esc_html($k).': '.esc_html($v).'</span>';echo '</div><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="sfc_generate">';wp_nonce_field('sfc_action');
        echo '<p><button class="button button-primary" type="submit">Поставить CREATE в очередь</button> <label>Лимит <input type="number" name="limit" value="250" min="1" max="1000" style="width:90px"></label></p><div style="overflow:auto;max-height:650px"><table class="widefat striped"><thead><tr><th>Тип</th><th>Entity</th><th>Lang</th><th>Decision</th><th>Причина</th></tr></thead><tbody>';
        foreach(array_slice($rows,0,1000) as $r){$entity=get_the_title($r['entity_id']);$rel=$r['related_id']?get_the_title($r['related_id']):'';echo '<tr><td>'.esc_html($r['page_type']).'</td><td>'.esc_html($entity.($rel?' · '.$rel:'' )).'</td><td>'.esc_html(strtoupper($r['lang'])).'</td><td><strong>'.esc_html($r['decision']).'</strong></td><td>'.esc_html($r['reason']).'</td></tr>';}
        echo '</tbody></table></div></form><div class="sfc-panel"><h2>Ручные Collection / Comparison</h2><p>Укажите ID товаров через запятую. Эти типы не проходят слепой гео-перебор.</p><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="sfc_manual">'.wp_nonce_field('sfc_action','_wpnonce',true,false).'<p><select name="manual_type"><option value="collection">Collection</option><option value="comparison">Comparison</option></select> <select name="manual_lang"><option value="uk">UA</option><option value="ru">RU</option></select> <input class="regular-text" name="product_ids" placeholder="1,2,3"></p><p><button class="button" type="submit">Поставить в очередь</button></p></form></div></div>';
    }
    public static function queue(){
        if(!current_user_can('manage_options'))return;$stats=SFC_DB::get_stats();$rows=array();global $wpdb;$rows=$wpdb->get_results('SELECT * FROM '.SFC_DB::jobs_table().' ORDER BY id DESC LIMIT 100',ARRAY_A);
        echo '<div class="wrap sfc-admin"><h1>Очередь</h1><p>Queued: '.$stats['queued'].' · Processing: '.$stats['processing'].' · Done: '.$stats['done'].' · Failed: '.$stats['failed'].'</p><p><a class="button" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=sfc_retry'),'sfc_action')).'">Повторить ошибки</a></p><table class="widefat striped"><thead><tr><th>ID</th><th>Тип</th><th>Статус</th><th>Попытки</th><th>Ошибка</th><th>Создан</th></tr></thead><tbody>';foreach($rows as $r)echo '<tr><td>'.(int)$r['id'].'</td><td>'.esc_html($r['job_type']).'</td><td>'.esc_html($r['status']).'</td><td>'.(int)$r['attempts'].'</td><td>'.esc_html($r['last_error']).'</td><td>'.esc_html($r['created_at']).'</td></tr>';echo '</tbody></table></div>';
    }
    public static function settings(){
        if(!current_user_can('manage_options'))return;$settings=SFC_Settings::get();$themes=array('premium-dark'=>'Premium Dark','modern-light'=>'Modern Light','neon-cyber'=>'Neon / Cyber','editorial-luxury'=>'Editorial / Luxury','dynamic-marketplace'=>'Dynamic Marketplace');
        echo '<div class="wrap sfc-admin"><h1>Дизайн и настройки</h1><form method="post" action="options.php">';settings_fields('sfc_settings_group');echo '<div class="sfc-panel"><h2>Тема сайта</h2><div class="sfc-theme-grid">';foreach($themes as $key=>$label){echo '<label class="sfc-theme-option"><input type="radio" name="sfc_settings[theme]" value="'.esc_attr($key).'" '.checked($settings['theme'],$key,false).'><span class="sfc-theme-preview '.esc_attr('sfc-theme-'.$key).'" data-theme="'.esc_attr($key).'">'.esc_html($label).'</span></label>';};echo '</div></div><div class="sfc-panel"><h2>Основные параметры</h2><table class="form-table">';
        self::row('sfc_settings[site_name]','Название сайта',$settings['site_name']);self::row('sfc_settings[region_min_cities]','Минимум активных городов для region landing',$settings['region_min_cities'],'number');self::row('sfc_settings[queue_batch]','Jobs за один cron tick',$settings['queue_batch'],'number');self::row('sfc_settings[similarity_threshold]','Порог схожести',$settings['similarity_threshold'],'number','min="0.60" max="0.95" step="0.01"');self::row('sfc_settings[cta_label_uk]','CTA UA',$settings['cta_label_uk']);self::row('sfc_settings[cta_label_ru]','CTA RU',$settings['cta_label_ru']);self::row('sfc_settings[cta_url]','CTA URL',$settings['cta_url']);echo '</table><label><input type="checkbox" name="sfc_settings[city_require_local_fact]" value="1" '.checked($settings['city_require_local_fact'],1,false).'> Для Product+City требовать локальные данные города</label><br><label><input type="checkbox" name="sfc_settings[product_city_require_query_or_allowlist]" value="1" '.checked($settings['product_city_require_query_or_allowlist'],1,false).'> Требовать local query / allowlist / geo flag</label></div>';
        echo '<div class="sfc-panel"><h2>Editorial Profile</h2><p>30 параметров являются управляющими сигналами для deterministic variation, а не «магическими уровнями текста».</p><table class="widefat striped"><thead><tr><th>Параметр</th><th>0–100</th></tr></thead><tbody>';foreach(SFC_Settings::profile_keys() as $key){echo '<tr><td>'.esc_html(ucwords(str_replace('_',' ',$key))).'</td><td><input type="range" min="0" max="100" name="sfc_settings[profile]['.esc_attr($key).']" value="'.(int)$settings['profile'][$key].'" oninput="this.nextElementSibling.value=this.value"><output>'.(int)$settings['profile'][$key].'</output></td></tr>';};echo '</tbody></table></div><p><button class="button button-primary">Сохранить</button></p></form></div>';
    }
    private static function row($name,$label,$value,$type='text',$extra=''){echo '<tr><th><label for="'.esc_attr($name).'">'.esc_html($label).'</label></th><td><input id="'.esc_attr($name).'" type="'.esc_attr($type).'" name="'.esc_attr($name).'" value="'.esc_attr($value).'" '.$extra.' class="regular-text"></td></tr>';}
    public static function generate(){if(!current_user_can('manage_options'))wp_die('Нет прав');check_admin_referer('sfc_action');$limit=max(1,min(1000,absint($_POST['limit']??250)));$count=SFC_Matrix::enqueue_create_jobs($limit);wp_safe_redirect(add_query_arg(array('page'=>'sfc-matrix','sfc_added'=>$count),admin_url('admin.php')));exit;}

    public static function manual(){
        if(!current_user_can('manage_options'))wp_die('Нет прав');check_admin_referer('sfc_action');
        $type=sanitize_key($_POST['manual_type']??'collection');$lang=($_POST['manual_lang']??'uk')==='ru'?'ru':'uk';
        $ids=array_values(array_unique(array_filter(array_map('absint',preg_split('/[^0-9]+/',(string)($_POST['product_ids']??''),-1,PREG_SPLIT_NO_EMPTY)))));
        if(count($ids)<2 || !in_array($type,array('collection','comparison'),true)){wp_safe_redirect(admin_url('admin.php?page=sfc-matrix'));exit;}
        $signature=hash('sha256',implode('|',array($type,implode(',',$ids),0,$lang)));
        SFC_Queue::enqueue('generate_page',array('page_type'=>$type,'entity_id'=>$ids,'related_id'=>0,'lang'=>$lang,'query'=>''));
        wp_safe_redirect(add_query_arg(array('page'=>'sfc-matrix','manual'=>'queued'),admin_url('admin.php')));exit;
    }
    public static function retry(){if(!current_user_can('manage_options'))wp_die('Нет прав');check_admin_referer('sfc_action');SFC_Queue::retry_failed();wp_safe_redirect(admin_url('admin.php?page=sfc-queue'));exit;}
    public static function seed(){if(!current_user_can('manage_options'))wp_die('Нет прав');check_admin_referer('sfc_action');self::seed_geo();wp_safe_redirect(admin_url('admin.php?page=sfc-dashboard'));exit;}
    public static function create_home(){if(!current_user_can('manage_options'))wp_die('Нет прав');check_admin_referer('sfc_action');$existing=get_page_by_path('site-factory-home');if(!$existing){$id=wp_insert_post(array('post_title'=>'Site Factory Home','post_name'=>'site-factory-home','post_status'=>'publish','post_type'=>'page','post_content'=>'[sf_home]'));}else $id=$existing->ID;update_option(SFC_Settings::OPTION,wp_parse_args(array('home_page_id'=>$id),SFC_Settings::get()));wp_safe_redirect(admin_url('admin.php?page=sfc-settings'));exit;}
    private static function seed_geo(){
        $regions=array(
            'Вінницька область'=>array('Вінниця','Жмеринка','Могилів-Подільський','Хмільник','Козятин'),'Волинська область'=>array('Луцьк','Ковель','Володимир','Нововолинськ','Камінь-Каширський'),'Дніпропетровська область'=>array('Дніпро','Кривий Ріг','Кам’янське','Нікополь','Павлоград'),'Житомирська область'=>array('Житомир','Бердичів','Коростень','Звягель','Малин'),'Закарпатська область'=>array('Ужгород','Мукачево','Хуст','Берегове','Виноградів'),'Запорізька область'=>array('Запоріжжя','Бердянськ','Мелітополь','Енергодар','Токмак'),'Івано-Франківська область'=>array('Івано-Франківськ','Калуш','Коломия','Надвірна','Долина'),'Київська область'=>array('Біла Церква','Бровари','Бориспіль','Вишневе','Фастів'),'Кіровоградська область'=>array('Кропивницький','Олександрія','Світловодськ','Знам’янка','Гайворон'),'Львівська область'=>array('Львів','Дрогобич','Червоноград','Стрий','Самбір'),'Миколаївська область'=>array('Миколаїв','Первомайськ','Южноукраїнськ','Вознесенськ','Очаків'),'Одеська область'=>array('Одеса','Чорноморськ','Ізмаїл','Білгород-Дністровський','Подільськ'),'Полтавська область'=>array('Полтава','Кременчук','Лубни','Миргород','Горішні Плавні'),'Рівненська область'=>array('Рівне','Дубно','Вараш','Сарни','Здолбунів'),'Сумська область'=>array('Суми','Конотоп','Шостка','Охтирка','Ромни'),'Тернопільська область'=>array('Тернопіль','Чортків','Кременець','Бережани','Збараж'),'Харківська область'=>array('Харків','Лозова','Ізюм','Чугуїв','Красноград'),'Херсонська область'=>array('Херсон','Нова Каховка','Каховка','Генічеськ','Скадовськ'),'Хмельницька область'=>array('Хмельницький','Кам’янець-Подільський','Шепетівка','Старокостянтинів','Нетішин'),'Черкаська область'=>array('Черкаси','Умань','Сміла','Золотоноша','Канів'),'Чернівецька область'=>array('Чернівці','Хотин','Новодністровськ','Кіцмань','Сторожинець'),'Чернігівська область'=>array('Чернігів','Ніжин','Прилуки','Новгород-Сіверський','Бахмач'),
        );
        foreach($regions as $name=>$cities){$rid=self::find_or_create_entity('sf_region',$name,array('_sfc_name_uk'=>$name,'_sfc_enable_landing'=>'0'));foreach($cities as $c){self::find_or_create_entity('sf_city',$c,array('_sfc_name_uk'=>$c,'_sfc_name_ru'=>$c,'_sfc_region_id'=>$rid,'_sfc_active'=>'1','_sfc_enable_landing'=>'0'));}}
    }
    private static function find_or_create_entity($type,$title,$meta){$existing=get_posts(array('post_type'=>$type,'post_status'=>array('publish','draft'),'posts_per_page'=>1,'title'=>$title,'fields'=>'ids'));$id=!empty($existing)?(int)$existing[0]:wp_insert_post(array('post_type'=>$type,'post_status'=>'draft','post_title'=>$title));foreach($meta as $k=>$v)if(get_post_meta($id,$k,true)==='')update_post_meta($id,$k,$v);return $id;}
}
