<?php
if (!defined('ABSPATH')) exit;
class UWSB_Admin {
    public static function init(){
        add_action('admin_menu',[__CLASS__,'menu']); add_action('admin_post_uwsb_create_project',[__CLASS__,'create']); add_action('admin_post_uwsb_generate',[__CLASS__,'generate']); add_action('admin_post_uwsb_publish',[__CLASS__,'publish']);
        add_action('admin_enqueue_scripts',function($hook){ if(str_contains($hook,'uwsb')) wp_enqueue_style('uwsb-admin',UWSB_URL.'assets/admin.css',[],UWSB_VERSION); });
    }
    public static function menu(){ add_menu_page('Site Factory','Site Factory','manage_options','uwsb', [__CLASS__,'dashboard'],'dashicons-layout',3); add_submenu_page('uwsb','Новый проект','Новый проект','manage_options','uwsb-new',[__CLASS__,'wizard']); }
    public static function dashboard(){ if(!current_user_can('manage_options'))return; global $wpdb; $rows=$wpdb->get_results('SELECT * FROM '.UWSB_DB::t('projects').' ORDER BY id DESC LIMIT 50',ARRAY_A); echo '<div class="wrap uwsb-admin"><h1>Site Factory</h1><p>Site compiler: data → plan → design → links → QA → publish.</p><p><a class="button button-primary" href="'.esc_url(admin_url('admin.php?page=uwsb-new')).'">Создать сайт</a></p><div class="uwsb-list">'; foreach($rows as $r){ echo '<div class="uwsb-project"><h2>'.esc_html($r['name']).'</h2><p>'.esc_html(strtoupper($r['profile']).' · '.$r['site_type'].' · '.$r['lang'].' · '.$r['status']).'</p><a class="button" href="'.esc_url(admin_url('admin.php?page=uwsb&project='.(int)$r['id'])).'">Открыть</a></div>'; } echo '</div>'; if(isset($_GET['project']))self::project_view(absint($_GET['project'])); echo '</div>'; }
    public static function wizard(){ if(!current_user_can('manage_options'))return; $profiles=UWSB_Profiles::all(); echo '<div class="wrap uwsb-admin"><h1>Новый сайт</h1><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="uwsb_create_project">'; wp_nonce_field('uwsb_create_project'); echo '<div class="uwsb-panel"><h2>1. Проект</h2><p><input class="regular-text" name="name" required placeholder="Название проекта"></p><p><select name="site_type"><option value="catalog">Каталог</option><option value="company">Компания / услуги</option><option value="leadgen">Lead generation</option><option value="store">Магазин</option><option value="informational">Информационный</option></select> <select name="lang"><option value="uk">UA</option><option value="ru">RU</option></select></p></div><div class="uwsb-panel"><h2>2. Товары / услуги</h2><p>Одна строка: <code>Название | факт | факт | price: 100</code></p><textarea name="items_raw" rows="9" class="large-text"></textarea></div><div class="uwsb-panel"><h2>3. Запросы / география / контакты</h2><textarea name="queries_raw" rows="5" class="large-text" placeholder="Поисковые запросы — по одному на строку"></textarea><textarea name="geography_raw" rows="4" class="large-text" placeholder="Реальная география работы / доставки"></textarea><textarea name="contacts_raw" rows="4" class="large-text" placeholder="Контактные данные"></textarea></div><div class="uwsb-panel"><h2>4. Характер сайта</h2><div class="uwsb-profiles">'; foreach($profiles as $k=>$p) echo '<label><input type="radio" name="profile" value="'.esc_attr($k).'" '.checked($k,'businessman',false).'><span><strong>'.esc_html($p['label']).'</strong><small>'.esc_html($p['hero'].' / '.$p['tone']).'</small></span></label>'; echo '</div></div><p><button class="button button-primary button-hero">Создать Site Plan</button></p></form></div>'; }
    public static function create(){ if(!current_user_can('manage_options'))wp_die('Forbidden'); check_admin_referer('uwsb_create_project'); $profiles=array_keys(UWSB_Profiles::all()); $profile=sanitize_key($_POST['profile']??'businessman'); if(!in_array($profile,$profiles,true))$profile='businessman'; $lang=($_POST['lang']??'uk')==='ru'?'ru':'uk'; $site_type=sanitize_key($_POST['site_type']??'catalog'); if(!in_array($site_type,['catalog','company','leadgen','store','informational'],true))$site_type='catalog'; $name=sanitize_text_field($_POST['name']??''); if(!$name)wp_die('Название обязательно'); $config=['name'=>$name,'lang'=>$lang,'items_raw'=>sanitize_textarea_field($_POST['items_raw']??''),'queries_raw'=>sanitize_textarea_field($_POST['queries_raw']??''),'geography_raw'=>sanitize_textarea_field($_POST['geography_raw']??''),'contacts_raw'=>sanitize_textarea_field($_POST['contacts_raw']??'')]; $id=UWSB_DB::create_project(['name'=>$name,'site_type'=>$site_type,'lang'=>$lang,'profile'=>$profile,'config'=>$config]); UWSB_Engine::plan_project($id); wp_safe_redirect(admin_url('admin.php?page=uwsb&project='.$id)); exit; }
    private static function project_view($id){ $p=UWSB_DB::project($id); if(!$p)return; $plans=UWSB_DB::plans($id); $qa=UWSB_QA::run($id); echo '<hr><h2>'.esc_html($p['name']).'</h2><p><strong>Site Plan:</strong> '.count($plans).' pages</p><table class="widefat striped"><thead><tr><th>Type</th><th>Page</th><th>Status</th><th>Preview</th></tr></thead><tbody>'; foreach($plans as $r){ echo '<tr><td>'.esc_html($r['page_type']).'</td><td>'.esc_html($r['page_key']).'</td><td>'.esc_html($r['status']).'</td><td>'.($r['wp_post_id']?'<a target="_blank" href="'.esc_url(get_preview_post_link((int)$r['wp_post_id'])).'">Preview</a>':'—').'</td></tr>'; } echo '</tbody></table><p><a class="button button-primary" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=uwsb_generate&project='.$id),'uwsb_generate')).'">Generate / Resume</a> <a class="button" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=uwsb_publish&project='.$id),'uwsb_publish')).'">Publish site</a></p><h3>QA</h3>'; if(!$qa)echo '<p>Нет проблем.</p>'; else {echo '<ul>'; foreach($qa as $i) echo '<li><strong>'.esc_html($i['severity']).'</strong> '.esc_html($i['code']).' — '.esc_html($i['message']).'</li>'; echo '</ul>';}}
    public static function generate(){ if(!current_user_can('manage_options'))wp_die('Forbidden'); check_admin_referer('uwsb_generate'); $id=absint($_GET['project']??0); UWSB_Engine::process_jobs(50,$id); UWSB_QA::run($id); wp_safe_redirect(admin_url('admin.php?page=uwsb&project='.$id)); exit; }
    public static function publish(){ if(!current_user_can('manage_options'))wp_die('Forbidden'); check_admin_referer('uwsb_publish'); $id=absint($_GET['project']??0); $r=UWSB_Engine::publish_project($id); $args=['page'=>'uwsb','project'=>$id]; if(is_wp_error($r))$args['uwsb_error']=$r->get_error_code(); wp_safe_redirect(add_query_arg($args,admin_url('admin.php'))); exit; }
}